# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/MapQuest/podspecs-ios.git'

target 'Survival' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Survival
  pod 'MapQuestMaps', '3.2.1-1.2'

  target 'SurvivalTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SurvivalUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
